import Head from "next/head"
import "swiper/css"
import "swiper/css/pagination"
import StartComponent from "@/components/StartComponent"
import YonalishlarComponent from "@/components/YonalishlarComponent";
import styled from "styled-components";
import BannerComponent from "@/components/BannerComponent";
import BannerBottomComponent from "@/components/BannerBottomComponent";
import YangiliklarComponent from "@/components/YangiliklarComponent";
import VideoBolimComponent from "@/components/VideoBolimComponent";
import BizningHamkorComponent from "@/components/BizningHamkorComponent";
import BackImgComponent from "@/components/BackImgComponent";
import Footer from "@/components/Footer";

const Index = () => {

    const Container = styled.main`
      display: flex;
      flex-direction: column;
      gap: 60px;
    `

    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta property="og:title" content="What Is a Meta Description How to Write One"/>
                <meta name="robots" content="index, follow"/>
                <meta name="keywords"
                      content="peshqadamkarvoni.uz peshqadamkarvoni shayx muhammad sodiq muhammad yusuf rahimahullohning muborak hayotlari va yorqin ilm yoʻllarini davom ettirish"/>
                <meta name="author" content="Odinaxon bintu Sodiq"/>
                <meta
                    name="description"
                    content="shayx muhammad sodiq muhammad yusuf rahimahullohning muborak hayotlari va yorqin ilm yoʻllarini davom ettirish"
                />
                <meta name="google-site-verification" content="+nxGUDJ4QpAZ5l9Bsjdi102tLVC21AIh5d1Nl23908vVuFHs34=" />
                <meta http-equiv="refresh" content="30"/>
                <title>Peshqadam karvoni</title>
            </Head>
            <Container>
                <StartComponent />
                <YonalishlarComponent />
                <BannerComponent />
                <BannerBottomComponent />
                <YangiliklarComponent />
                <VideoBolimComponent />
                <BizningHamkorComponent />
                <BackImgComponent />
                <Footer />
            </Container>
        </>
    );
}

export default Index