import Head from "next/head"
import Navbar from "@/components/Navbar";
import StartCom from "@/components/homaPageComponents/StartCom"
import "swiper/css"
import "swiper/css/pagination"
import YonalishlarCom from "@/components/homaPageComponents/YonalishlarCom"
import YangiliklarCom from "@/components/homaPageComponents/YangiliklarCom";
import Footer from "@/components/Footer";

const Index = () => {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <meta property="og:title" content="What Is a Meta Description How to Write One"/>
                <meta name="robots" content="index, follow"/>
                <meta name="keywords"
                      content="peshqadamkarvoni.uz peshqadamkarvoni shayx muhammad sodiq muhammad yusuf rahimahullohning muborak hayotlari va yorqin ilm yoʻllarini davom ettirish"/>
                <meta name="author" content="Odinaxon bintu Sodiq"/>
                <meta
                    name="description"
                    content="shayx muhammad sodiq muhammad yusuf rahimahullohning muborak hayotlari va yorqin ilm yoʻllarini davom ettirish"
                />
                <meta name="google-site-verification" content="+nxGUDJ4QpAZ5l9Bsjdi102tLVC21AIh5d1Nl23908vVuFHs34=" />
                <meta http-equiv="refresh" content="30"/>
                <title>Peshqadam karvoni</title>
            </Head>
            <main>
                <Navbar>
                    <StartCom />
                    <YonalishlarCom />
                    <YangiliklarCom />
                </Navbar>
                <Footer />
            </main>
        </>
    );
}

export default Index